spring:
  application:
    name: nospf-bootstrapping-poc
    version: replaceVersion

# embedded Tomcat
server:
  port: 9900

logging:
  level:
    root: WARN
    ru: DEBUG

jsondb:
  dbFilesLocation: c:/nospf/storage

nospf-bootstrapping-poc:
  node-info:
    network-id: QwErAsD
    node-bucket: 0
    port: 56789
  scan-dns-params:
    domains:
    - duckdns.org
    - mine.nu
    first-port: 56780
    last-port: 65000
    last-node-bucket: 10000